names = {'profits': 'satisficing score',
         "private agents": 'firms',
         "public agents": 'policy makers',
         "LSS_weak": 'Change in effort',
         "LSS_tot": 'Adaptations',
         "current_state": 'satisficing score',
         "current_state_norm": 'satisficing score',
         "05_YES_YES": 'Half homogeneity (public financing and auctions) - ',
         "1_YES_YES": 'No homogeneity (public financing and auctions) - ',
         "0_YES_YES": 'Full homogeneity (public financing and auctions) - ',
         "1_YES_NO": 'Just public bank - ',
         "1_NO_YES": 'Just energy policy maker - ',
         "1_NO_NO": 'No policy maker - ',
         "025_YES_YES": "A quarter homogeneity (public financing and auctions) - ",
         "075_YES_YES": "Three quarters homogeneity (public financing and auctions) - ",
         "0_YES_YES_YES": "Full homogeneity - ",
         "period": 'Period'
         }
